package cmd

import (
	"fmt"
	"os"
	"strings"
	"text/tabwriter"

	"github.com/inovacc/repited/internal/store"
	"github.com/spf13/cobra"
)

var relationsCmd = &cobra.Command{
	Use:   "relations",
	Short: "Show how Claude Code commands relate to each other",
	Long: `Analyze command co-occurrence and sequencing patterns from stored scan data.
Shows which tools Claude Code uses together, in what order, and grouped by workflow category.

All .scripts/ folders are generated by Claude Code sessions — this command
reveals the underlying workflow patterns: what commands precede others,
which tools always appear together, and how Claude Code structures its scripts.`,
	RunE: runRelations,
}

func init() {
	rootCmd.AddCommand(relationsCmd)

	relationsCmd.Flags().StringP("db", "", defaultDBPath(), "SQLite database path")
	relationsCmd.Flags().Int64P("scan", "s", 0, "scan ID (0 = latest)")
	relationsCmd.Flags().IntP("min", "m", 5, "minimum occurrence count to show")
	relationsCmd.Flags().IntP("limit", "n", 40, "max rows per section")
	relationsCmd.Flags().BoolP("sequences", "", true, "show A→B sequential pairs")
	relationsCmd.Flags().BoolP("cooccur", "", true, "show co-occurrence pairs")
	relationsCmd.Flags().BoolP("positions", "", true, "show tool position analysis (first/middle/last)")
	relationsCmd.Flags().BoolP("clusters", "", true, "show tool clusters by category")
}

func runRelations(cmd *cobra.Command, _ []string) error {
	dbPath, _ := cmd.Flags().GetString("db")
	scanID, _ := cmd.Flags().GetInt64("scan")
	minCount, _ := cmd.Flags().GetInt("min")
	limit, _ := cmd.Flags().GetInt("limit")
	showSeq, _ := cmd.Flags().GetBool("sequences")
	showCooccur, _ := cmd.Flags().GetBool("cooccur")
	showPos, _ := cmd.Flags().GetBool("positions")
	showClusters, _ := cmd.Flags().GetBool("clusters")

	if _, err := os.Stat(dbPath); os.IsNotExist(err) {
		return fmt.Errorf("database not found at %s — run 'repited scan' first", dbPath)
	}

	db, err := store.Open(dbPath)
	if err != nil {
		return fmt.Errorf("opening database: %w", err)
	}

	defer func() { _ = db.Close() }()

	// Resolve scan ID
	if scanID == 0 {
		scans, err := db.ListScans()
		if err != nil {
			return fmt.Errorf("listing scans: %w", err)
		}

		if len(scans) == 0 {
			_, _ = fmt.Fprintln(os.Stdout, "No scans found.")
			return nil
		}

		scanID = scans[0].ID
		_, _ = fmt.Fprintf(os.Stdout, "Analyzing scan #%d (%s)\n\n", scanID, scans[0].RootDir)
	}

	if showClusters {
		if err := printClusters(db, scanID); err != nil {
			return err
		}
	}

	if showSeq {
		if err := printSequences(db, scanID, minCount, limit); err != nil {
			return err
		}
	}

	if showCooccur {
		if err := printCooccurrences(db, scanID, minCount, limit); err != nil {
			return err
		}
	}

	if showPos {
		if err := printPositions(db, scanID, limit); err != nil {
			return err
		}
	}

	return nil
}

func printClusters(db *store.Store, scanID int64) error {
	clusters, err := db.ToolClusters(scanID)
	if err != nil {
		return fmt.Errorf("querying clusters: %w", err)
	}

	_, _ = fmt.Fprintln(os.Stdout, "═══ TOOL CLUSTERS (by category) ═══")
	_, _ = fmt.Fprintln(os.Stdout)

	for _, cl := range clusters {
		total := 0
		for _, t := range cl.Tools {
			total += t.Count
		}

		_, _ = fmt.Fprintf(os.Stdout, "┌─ %s (%d total invocations)\n", cl.Category, total)

		for i, t := range cl.Tools {
			connector := "├─"
			if i == len(cl.Tools)-1 {
				connector = "└─"
			}

			barLen := max((t.Count*20)/cl.Tools[0].Count, 1)

			bar := strings.Repeat("█", barLen)
			_, _ = fmt.Fprintf(os.Stdout, "│  %s %-20s %4d  %s\n", connector, t.Tool, t.Count, bar)
		}

		_, _ = fmt.Fprintln(os.Stdout)
	}

	return nil
}

func printSequences(db *store.Store, scanID int64, minCount int, limit int) error {
	seqs, err := db.ToolSequences(scanID, minCount, limit)
	if err != nil {
		return fmt.Errorf("querying sequences: %w", err)
	}

	if len(seqs) == 0 {
		_, _ = fmt.Fprintln(os.Stdout, "No sequential patterns found (try lowering --min).")
		return nil
	}

	_, _ = fmt.Fprintln(os.Stdout, "═══ COMMAND SEQUENCES (A → B within same script) ═══")
	_, _ = fmt.Fprintln(os.Stdout, "Shows which commands Claude Code runs before others.")
	_, _ = fmt.Fprintln(os.Stdout)

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	_, _ = fmt.Fprintln(w, "FROM\t→\tTO\tSCRIPTS\tPATTERN")

	maxCount := seqs[0].Count
	for _, r := range seqs {
		barLen := max((r.Count*20)/maxCount, 1)

		bar := strings.Repeat("▓", barLen)
		_, _ = fmt.Fprintf(w, "%s\t→\t%s\t%d\t%s\n", r.From, r.To, r.Count, bar)
	}

	_ = w.Flush()

	_, _ = fmt.Fprintln(os.Stdout)

	return nil
}

func printCooccurrences(db *store.Store, scanID int64, minCount int, limit int) error {
	pairs, err := db.ToolCooccurrences(scanID, minCount, limit)
	if err != nil {
		return fmt.Errorf("querying cooccurrences: %w", err)
	}

	if len(pairs) == 0 {
		_, _ = fmt.Fprintln(os.Stdout, "No co-occurrence patterns found (try lowering --min).")
		return nil
	}

	_, _ = fmt.Fprintln(os.Stdout, "═══ CO-OCCURRENCE (tools appearing in same script) ═══")
	_, _ = fmt.Fprintln(os.Stdout, "Shows which tools Claude Code always uses together.")
	_, _ = fmt.Fprintln(os.Stdout)

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	_, _ = fmt.Fprintln(w, "TOOL A\t↔\tTOOL B\tSCRIPTS\tSTRENGTH")

	maxCount := pairs[0].Count
	for _, p := range pairs {
		barLen := max((p.Count*20)/maxCount, 1)

		bar := strings.Repeat("░", barLen)
		_, _ = fmt.Fprintf(w, "%s\t↔\t%s\t%d\t%s\n", p.ToolA, p.ToolB, p.Count, bar)
	}

	_ = w.Flush()

	_, _ = fmt.Fprintln(os.Stdout)

	return nil
}

func printPositions(db *store.Store, scanID int64, limit int) error {
	steps, err := db.ToolPositions(scanID, limit*3)
	if err != nil {
		return fmt.Errorf("querying positions: %w", err)
	}

	if len(steps) == 0 {
		_, _ = fmt.Fprintln(os.Stdout, "No position data found.")
		return nil
	}

	// Group by position
	first := make([]store.WorkflowStep, 0)
	middle := make([]store.WorkflowStep, 0)
	last := make([]store.WorkflowStep, 0)

	for _, ws := range steps {
		switch ws.Position {
		case "first":
			if len(first) < limit {
				first = append(first, ws)
			}
		case "middle":
			if len(middle) < limit {
				middle = append(middle, ws)
			}
		case "last":
			if len(last) < limit {
				last = append(last, ws)
			}
		}
	}

	_, _ = fmt.Fprintln(os.Stdout, "═══ TOOL POSITIONS (where in scripts Claude Code places commands) ═══")
	_, _ = fmt.Fprintln(os.Stdout)

	printPositionGroup("STARTS WITH (first command)", first)
	printPositionGroup("MIDDLE STEPS", middle)
	printPositionGroup("ENDS WITH (last command)", last)

	return nil
}

func printPositionGroup(title string, steps []store.WorkflowStep) {
	if len(steps) == 0 {
		return
	}

	_, _ = fmt.Fprintf(os.Stdout, "  %s:\n", title)

	maxCount := steps[0].Count
	for _, ws := range steps {
		barLen := max((ws.Count*15)/maxCount, 1)

		bar := strings.Repeat("█", barLen)
		_, _ = fmt.Fprintf(os.Stdout, "    %-25s %4d  %s\n", ws.Tool, ws.Count, bar)
	}

	_, _ = fmt.Fprintln(os.Stdout)
}
